In [1]:
import numpy as np

arr = np.ones((3, 4))

In [2]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [4]:
arr * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [5]:
np.empty((3, 4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [6]:
np.eye(3, dtype = int) # n * n matrix    # To calculate inverse of matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# Optional

import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [9]:
# Extra topics
import random

print(random.choice((1, 2, 3, 4, 5, 6)))

print(random.choice('Rajdip'))
print(random.randrange(1, 10))
print(random.random()) # A random n is generated between 0 (included), 1 will be excluded

lis = [1, 2, 3, 4, 5]
random.shuffle(lis)
print(lis)

print(random.uniform(7, 14)) # A no. between 1 and 14

5
a
6
0.26558840511368453
[1, 3, 2, 4, 5]
12.037768779277334


In [10]:
np.array([])

array([], dtype=float64)

In [11]:
np.random.random_sample()

0.5972148573631172

In [12]:
type(np.random.random_sample())

float

In [13]:
np.random.random_sample((5,))

array([0.99241358, 0.22412654, 0.12539086, 0.36901074, 0.49477362])

In [14]:
np.random.rand(2, 3)

array([[0.01756541, 0.00876073, 0.12387652],
       [0.98849353, 0.40106612, 0.63996877]])

In [15]:
np.random.randn(2, 3)

array([[ 0.93105296, -0.45939277, -2.32434594],
       [-0.19352939, -3.2052947 ,  1.2489145 ]])

In [16]:
np.random.random_sample()

0.266625604245717

In [17]:
np.random.randint(1, 5, size=(3, 4))

array([[4, 2, 1, 4],
       [3, 3, 1, 3],
       [4, 4, 1, 1]])

In [18]:
arr = np.random.randint(1, 5, size=(3, 4))

In [19]:
arr

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [20]:
arr.size

12

In [21]:
arr.shape

(3, 4)

In [22]:
arr.ndim

2

In [23]:
arr

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [24]:
arr.reshape(2, 6)   # Array size not change, multiples of array size

array([[3, 4, 1, 3, 1, 2],
       [1, 3, 3, 1, 4, 4]])

In [25]:
arr.reshape(6, 2)

array([[3, 4],
       [1, 3],
       [1, 2],
       [1, 3],
       [3, 1],
       [4, 4]])

In [26]:
arr.reshape(12,)

array([3, 4, 1, 3, 1, 2, 1, 3, 3, 1, 4, 4])

In [27]:
arr.reshape(12, 1)

array([[3],
       [4],
       [1],
       [3],
       [1],
       [2],
       [1],
       [3],
       [3],
       [1],
       [4],
       [4]])

In [28]:
# arr.reshape(12, 2)

# ValueError: cannot reshape array of size 12 into shape (12,2)

In [29]:
arr.reshape(4, 3)

array([[3, 4, 1],
       [3, 1, 2],
       [1, 3, 3],
       [1, 4, 4]])

In [30]:
arr.reshape(3, 4)

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [31]:
arr

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [32]:
arr.reshape(4, -1)

array([[3, 4, 1],
       [3, 1, 2],
       [1, 3, 3],
       [1, 4, 4]])

In [33]:
arr.reshape(4, -100)

array([[3, 4, 1],
       [3, 1, 2],
       [1, 3, 3],
       [1, 4, 4]])

In [34]:
arr.reshape(3, -100)

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [35]:
arr.reshape(-1, 4)

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [36]:
arr

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [37]:
arr.reshape(12,).base

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [38]:
arr

array([[3, 4, 1, 3],
       [1, 2, 1, 3],
       [3, 1, 4, 4]])

In [39]:
arr.size

12

In [40]:
arr.reshape(2, 2, 3)

array([[[3, 4, 1],
        [3, 1, 2]],

       [[1, 3, 3],
        [1, 4, 4]]])

In [41]:
arr.reshape(1, 2, 2, 3)

array([[[[3, 4, 1],
         [3, 1, 2]],

        [[1, 3, 3],
         [1, 4, 4]]]])

In [42]:
arr.reshape(4, 3, 1)

array([[[3],
        [4],
        [1]],

       [[3],
        [1],
        [2]],

       [[1],
        [3],
        [3]],

       [[1],
        [4],
        [4]]])

In [43]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[3, 4, 1],
                 [3, 1, 2]],

                [[1, 3, 3],
                 [1, 4, 4]]]]]]]]]]]])

In [44]:
lis = [1, 2, 3, 4]

In [45]:
arr = np.array(lis)

In [46]:
arr

array([1, 2, 3, 4])

In [47]:
arr.ndim

1

In [48]:
arr2 = np.array([[2, 3], [4, 5]])
arr2

array([[2, 3],
       [4, 5]])

In [49]:
arr2.ndim

2

In [50]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
arr2.ndim

2

In [52]:
arr3 = np.zeros((1, 3, 4))      # 3 rows, 4 columns >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [53]:
arr3.ndim

3

In [54]:
arr4 = np.zeros((1, 1, 3, 4))   # 3 rows, 4 columns >> 2d array + 1d + 1d
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [55]:
arr4.ndim

4

In [56]:
arr4.shape

(1, 1, 3, 4)

In [57]:
arr3 = np.zeros((3, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [58]:
arr3.ndim

3

In [59]:
arr3.shape

(3, 3, 4)

In [60]:
arr1 = np.random.randint(1, 10, (5, 6))

In [61]:
arr1

array([[9, 6, 1, 2, 5, 5],
       [2, 4, 5, 2, 4, 6],
       [4, 5, 9, 4, 6, 7],
       [9, 9, 2, 9, 4, 9],
       [2, 2, 6, 4, 2, 3]])

In [62]:
arr1 > 5

array([[ True,  True, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False,  True, False,  True,  True],
       [ True,  True, False,  True, False,  True],
       [False, False,  True, False, False, False]])

In [63]:
arr1[arr1 > 5]

array([9, 6, 6, 9, 6, 7, 9, 9, 9, 9, 6])

In [64]:
arr1[arr1 < 5]

array([1, 2, 2, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 2, 3])

In [65]:
arr1

array([[9, 6, 1, 2, 5, 5],
       [2, 4, 5, 2, 4, 6],
       [4, 5, 9, 4, 6, 7],
       [9, 9, 2, 9, 4, 9],
       [2, 2, 6, 4, 2, 3]])

In [66]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
arr[0]

array([0., 0., 0., 0.])

In [68]:
arr1

array([[9, 6, 1, 2, 5, 5],
       [2, 4, 5, 2, 4, 6],
       [4, 5, 9, 4, 6, 7],
       [9, 9, 2, 9, 4, 9],
       [2, 2, 6, 4, 2, 3]])

In [69]:
arr1[0:2, [0, 2]] # 0th - 1st row in continuation and 0th and 2nd column

array([[9, 1],
       [2, 5]])

In [70]:
# Slicing on both rows and column
arr1[0:2, 1:3]

array([[6, 1],
       [4, 5]])

In [71]:
arr1[0:2, [0, 1]]

array([[9, 6],
       [2, 4]])

In [72]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
arr1[0, [1, 3]]

array([6, 2])

In [74]:
arr1[2:4, [0, 2]]

array([[4, 9],
       [9, 2]])

In [75]:
arr1

array([[9, 6, 1, 2, 5, 5],
       [2, 4, 5, 2, 4, 6],
       [4, 5, 9, 4, 6, 7],
       [9, 9, 2, 9, 4, 9],
       [2, 2, 6, 4, 2, 3]])

In [76]:
arr1[2:5]

array([[4, 5, 9, 4, 6, 7],
       [9, 9, 2, 9, 4, 9],
       [2, 2, 6, 4, 2, 3]])

In [77]:
arr1[2:5, 0:2]   # Slicing

array([[4, 5],
       [9, 9],
       [2, 2]])

In [78]:
arr1[2:5, [0, 2]]

array([[4, 9],
       [9, 2],
       [2, 6]])

In [79]:
arr1[[2,4]]

array([[4, 5, 9, 4, 6, 7],
       [2, 2, 6, 4, 2, 3]])

In [80]:
arr1

array([[9, 6, 1, 2, 5, 5],
       [2, 4, 5, 2, 4, 6],
       [4, 5, 9, 4, 6, 7],
       [9, 9, 2, 9, 4, 9],
       [2, 2, 6, 4, 2, 3]])

In [81]:
arr1[[2, 4]] # selecting specific column

array([[4, 5, 9, 4, 6, 7],
       [2, 2, 6, 4, 2, 3]])

In [82]:
arr1[2 : 4] # slicing

array([[4, 5, 9, 4, 6, 7],
       [9, 9, 2, 9, 4, 9]])

In [83]:
arr1

array([[9, 6, 1, 2, 5, 5],
       [2, 4, 5, 2, 4, 6],
       [4, 5, 9, 4, 6, 7],
       [9, 9, 2, 9, 4, 9],
       [2, 2, 6, 4, 2, 3]])

In [84]:
arr1[2:4, [1, 3]]

array([[5, 4],
       [9, 9]])

In [85]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [86]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [87]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [88]:
arr1 + arr2

array([[3, 3, 3],
       [4, 2, 3],
       [4, 2, 4]])

In [89]:
arr1 - arr2

array([[-1, -1,  1],
       [ 0,  0,  1],
       [ 0,  0,  0]])

In [90]:
arr1 * arr2

array([[2, 2, 2],
       [4, 1, 2],
       [4, 1, 4]])

In [91]:
# matrix multiplication

arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [92]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [93]:
arr1 @ arr2

array([[ 8,  5,  6],
       [10,  7,  7],
       [10,  7,  7]])

In [94]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [95]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [96]:
arr1 / arr2 # Index wise divison

array([[0.5, 0.5, 2. ],
       [1. , 1. , 2. ],
       [1. , 1. , 1. ]])

In [97]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [98]:
arr1 / 0

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1664\824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [99]:
#Broad casting

In [100]:
arr = np.zeros((3, 4))

In [101]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [103]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
a = np.array([1, 2, 3, 4])

In [105]:
a.shape

(4,)

In [106]:
a

array([1, 2, 3, 4])

In [107]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [108]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
a

array([1, 2, 3, 4])

In [110]:
a = np.array([1, 2, 3])

In [111]:
a = np.array([[1, 2, 3]])

In [112]:
a

array([[1, 2, 3]])

In [113]:
a.T

array([[1],
       [2],
       [3]])

In [114]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [115]:
a

array([[1, 2, 3]])

In [116]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [117]:
a.T

array([[1],
       [2],
       [3]])

In [118]:
a = np.array([1, 2, 3])
a.T

array([1, 2, 3])

In [119]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [120]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356]])

In [121]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.30103]])

In [122]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [123]:
a

array([1, 2, 3])

In [124]:
np.min(a)

1

In [125]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [126]:
np.min(arr1)

1

In [127]:
np.max(arr1)

2

In [128]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [129]:
arr1.T

array([[1, 2, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [130]:
arr1.flatten() # Reduce higher dimension to 1D

array([1, 1, 2, 2, 1, 2, 2, 1, 2])

In [131]:
# expand_dims >>  expands the array by inserting a new axis

In [132]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

In [133]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [134]:
np.sum(arr)

27

In [135]:
np.sum(arr, axis=0)

array([ 6,  9, 12])

In [136]:
np.sum(arr, axis=1)

array([ 6, 15,  6])

In [137]:
# expand_dims >> expand the dimension of array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [138]:
arr.ndim

1

In [139]:
arr1 = np.expand_dims(arr, axis=0)

In [140]:
arr1

array([[1, 2, 3, 4]])

In [141]:
arr1.ndim

2

In [142]:
arr2 = np.expand_dims(arr1, axis=0)

In [143]:
arr2

array([[[1, 2, 3, 4]]])

In [144]:
arr2.shape

(1, 1, 4)

In [145]:
arr

array([1, 2, 3, 4])

In [146]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [147]:
arr = np.zeros((3, 4))

In [148]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [149]:
arr1 = np.expand_dims(arr, axis=1)

In [150]:
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [151]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])