### 1. What is a Python library? Why do we use Python libraries?

- **Python library:** A python library is a collection of pre-written, reusable code modules or functions that can be imported and used in our python scripts or programs. These libraries provide a set of tools and functionalities that can save our time and effort when developing software.
- We use python libraries because of - Code Reusability, Modularity, Performance Optimizations, Standardization, Ease of Development etc.

### 2. What is the difference between Numpy array and List?

- Numpy arrays are homogeneous means all elements in the array must be of the same data type, but Lists are heterogeneous means we can store different data types in the list.
- Numpy arrays are more efficient for numerical operations, especially when working with large datasets, but Lists are generally slower than Numpy arrays.
- Numpy arrays are more memory-efficient compared to lists, especially for large datasets, but Lists may consume more memory due to their flexibility in handling different data types.

### 3. Find the shape, size and dimension of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The array:\n", arr)
print()
print("Shape of the array:", arr.shape)
print("Size of the array:", arr.size)
print("Dimension of the array:", arr.ndim)

The array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


### 4. Write python code to access the first row of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The array:\n", arr)
print()
print("First row of the array:\n", arr[0])

The array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row of the array:
 [1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [3]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The array:\n", arr)
print()
print("Element at third row and fourth column:", arr[2, 3])

The array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at third row and fourth column: 12


### 6. Write code to extract all odd-indexed elements from the given numpy array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The array:\n", arr)
print()
print("Odd-indexed elements by column:\n", arr[:, 1::2])
print("\nOdd-indexed elements by row:\n", arr[1::2, :])
print("\nOdd-indexed elements by row & column:\n", arr[1::2, 1::2])

The array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Odd-indexed elements by column:
 [[ 2  4]
 [ 6  8]
 [10 12]]

Odd-indexed elements by row:
 [[5 6 7 8]]

Odd-indexed elements by row & column:
 [[6 8]]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [5]:
print("Random 3x3 matrix with values between 0 and 1:")
print(np.random.random_sample((3, 3)))

Random 3x3 matrix with values between 0 and 1:
[[0.48081316 0.1834967  0.13457106]
 [0.84884561 0.08726947 0.62203352]
 [0.29542743 0.57585626 0.46918913]]


### 8. Describe the difference between np.random.rand and np.random.randn?

- `np.random.rand`: This function generates random numbers from a uniform distribution between 0 (inclusive) and 1 (exclusive).
- `np.random.randn`: This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1), also known as a Gaussian or normal distribution.

### 9. Write code to increase the dimension of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [6]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The array:\n", arr)
print()
print("Expand the dimension by row:")
print(np.expand_dims(arr, axis=0))

The array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expand the dimension by row:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


### 10. How to transpose the following array in NumPy?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [7]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The array:\n", arr)
print()
print("Transpose of the array:")
print(arr.T)

The array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose of the array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consider the following matrix:
### Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
<br>

### Perform the following operation using Python:
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [8]:
matrix1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)

print("\n1. Index wise multiplication\n", matrix1 * matrix2)

## Matrix multiplication can't be happen because matrix1 = 3x4 and matrix2 = 3x4
# print("\n2. Matrix multiplication\n", matrix1 @ matrix2)      # This throws ValueError

## For perform matrix multiplication we have to transpose of matrix1 or matrix2
print("\n2. Matrix multiplication\n", matrix1 @ matrix2.T)

print("\n3. Add both the matrics\n", matrix1 + matrix2)
print("\n4. Subtract matrix B from A\n",matrix1 - matrix2)
print("\n5. Divide matrix B by A\n", matrix1 / matrix2)

Matrix 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1. Index wise multiplication
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Add both the matrics
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Subtract matrix B from A
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Divide matrix B by A
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12. Which function in Numpy can be used to swap the byte order of an array?

- In NumPy, we can use the `byteswap` function to swap the byte order of an array. The `byteswap` function is available for ndarray objects and allows us to change the endianness (byte order) of the data in the array.

### 13. What is the significance of the np.linalg.inv function?

- The `np.linalg.inv` function in NumPy is used to compute the multiplicative inverse of a matrix. In other words, it calculates the inverse of a square matrix, assuming it is invertible (non-singular). The result of the `np.linalg.inv` function is a matrix that, when multiplied with the original matrix, yields the identity matrix.

### 14. What does the np.reshape function do, and how is it used?

- The `np.reshape` function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array and give it a new shape.

```python
import numpy

arr = [[1, 2], [3, 4], [5, 6]]
numpy.reshape(arr, (2, 3))
```

- **Output**
```py
array([[1, 2, 3],
       [4, 5, 6]])
```

### 15. What is broadcasting in Numpy?

- Broadcasting is a powerful feature in NumPy that allows arrays of different shapes to be combined in arithmetic operations. It provides a set of rules for performing element-wise operations on arrays of different shapes, making it possible to operate on arrays that do not have the same dimensions.