In [1]:
import numpy as np
data = np.array([[1], [2], [3]])

In [2]:
data.ndim

2

In [3]:
data

array([[1],
       [2],
       [3]])

In [4]:
a = np.squeeze(data)

In [5]:
a.ndim

1

In [6]:
# repeat
data

array([[1],
       [2],
       [3]])

In [7]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [8]:
a = np.array([[1, 2], [3, 4]])

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [11]:
np.repeat(a, 2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [12]:
np.repeat(a, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [13]:
data

array([[1],
       [2],
       [3]])

In [14]:
np.roll(data, 1)

array([[3],
       [1],
       [2]])

In [15]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [16]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
a = np.array([[[1, 2], [3, 4], [5, 6]]])

In [18]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
np.roll(a, 2, axis=1)

array([[[3, 4],
        [5, 6],
        [1, 2]]])

In [20]:
# Binary operation on array

In [21]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [22]:
arr1

array([[6, 9, 7, 1],
       [1, 8, 8, 5],
       [5, 9, 6, 1]])

In [23]:
arr2

array([[6, 5, 8, 4],
       [6, 8, 9, 2],
       [8, 7, 4, 9]])

In [24]:
arr1 + arr2

array([[12, 14, 15,  5],
       [ 7, 16, 17,  7],
       [13, 16, 10, 10]])

In [25]:
arr1 - arr2

array([[ 0,  4, -1, -3],
       [-5,  0, -1,  3],
       [-3,  2,  2, -8]])

In [26]:
arr1 * arr2

array([[36, 45, 56,  4],
       [ 6, 64, 72, 10],
       [40, 63, 24,  9]])

In [27]:
arr1 / arr2

array([[1.        , 1.8       , 0.875     , 0.25      ],
       [0.16666667, 1.        , 0.88888889, 2.5       ],
       [0.625     , 1.28571429, 1.5       , 0.11111111]])

In [28]:
arr1 ** arr2

array([[    46656,     59049,   5764801,         1],
       [        1,  16777216, 134217728,        25],
       [   390625,   4782969,      1296,         1]])

In [29]:
arr1 > arr2

array([[False,  True, False, False],
       [False, False, False,  True],
       [False,  True,  True, False]])

In [30]:
~arr1

array([[ -7, -10,  -8,  -2],
       [ -2,  -9,  -9,  -6],
       [ -6, -10,  -7,  -2]])

In [31]:
arr1

array([[6, 9, 7, 1],
       [1, 8, 8, 5],
       [5, 9, 6, 1]])

In [32]:
# NumPy string function

In [33]:
arr = np.array(['pw', 'Skills'])

In [34]:
arr

array(['pw', 'Skills'], dtype='<U6')

In [35]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [36]:
np.char.lower(arr)

array(['pw', 'skills'], dtype='<U6')

In [37]:
np.char.upper(np.array(["Rajdip"]))

array(['RAJDIP'], dtype='<U6')

In [38]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [39]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [40]:
# Mathematical Function

arr1

array([[6, 9, 7, 1],
       [1, 8, 8, 5],
       [5, 9, 6, 1]])

In [41]:
np.sin(arr1)

array([[-0.2794155 ,  0.41211849,  0.6569866 ,  0.84147098],
       [ 0.84147098,  0.98935825,  0.98935825, -0.95892427],
       [-0.95892427,  0.41211849, -0.2794155 ,  0.84147098]])

In [42]:
np.cos(arr1)

array([[ 0.96017029, -0.91113026,  0.75390225,  0.54030231],
       [ 0.54030231, -0.14550003, -0.14550003,  0.28366219],
       [ 0.28366219, -0.91113026,  0.96017029,  0.54030231]])

In [43]:
np.tan(arr1)

array([[-0.29100619, -0.45231566,  0.87144798,  1.55740772],
       [ 1.55740772, -6.79971146, -6.79971146, -3.38051501],
       [-3.38051501, -0.45231566, -0.29100619,  1.55740772]])

In [44]:
np.log10(arr1)

array([[0.77815125, 0.95424251, 0.84509804, 0.        ],
       [0.        , 0.90308999, 0.90308999, 0.69897   ],
       [0.69897   , 0.95424251, 0.77815125, 0.        ]])

In [45]:
np.exp(arr1)

array([[4.03428793e+02, 8.10308393e+03, 1.09663316e+03, 2.71828183e+00],
       [2.71828183e+00, 2.98095799e+03, 2.98095799e+03, 1.48413159e+02],
       [1.48413159e+02, 8.10308393e+03, 4.03428793e+02, 2.71828183e+00]])

In [46]:
np.power(arr1, 3)

array([[216, 729, 343,   1],
       [  1, 512, 512, 125],
       [125, 729, 216,   1]], dtype=int32)

In [47]:
np.mean(arr1)

5.5

In [48]:
np.max(arr1)

9

In [49]:
np.std(arr1)

2.9011491975882016

In [50]:
np.var(arr1)

8.416666666666666

In [51]:
arr1 - arr2

array([[ 0,  4, -1, -3],
       [-5,  0, -1,  3],
       [-3,  2,  2, -8]])

In [52]:
np.subtract(arr1, arr2)

array([[ 0,  4, -1, -3],
       [-5,  0, -1,  3],
       [-3,  2,  2, -8]])

In [53]:
arr1 * arr2

array([[36, 45, 56,  4],
       [ 6, 64, 72, 10],
       [40, 63, 24,  9]])

In [54]:
np.multiply(arr1, arr2)

array([[36, 45, 56,  4],
       [ 6, 64, 72, 10],
       [40, 63, 24,  9]])

In [55]:
np.mod(arr1, arr2)  # Return element wise remainder

array([[0, 4, 7, 1],
       [1, 0, 8, 1],
       [5, 2, 2, 1]])

In [56]:
np.power(arr1, arr2)

array([[    46656,     59049,   5764801,         1],
       [        1,  16777216, 134217728,        25],
       [   390625,   4782969,      1296,         1]])

In [57]:
np.sqrt(arr1)

array([[2.44948974, 3.        , 2.64575131, 1.        ],
       [1.        , 2.82842712, 2.82842712, 2.23606798],
       [2.23606798, 3.        , 2.44948974, 1.        ]])

In [58]:
# sort search

In [59]:
arr = np.array([5, 6, 1, 2])

In [60]:
arr

array([5, 6, 1, 2])

In [61]:
np.sort(arr)

array([1, 2, 5, 6])

In [62]:
np.searchsorted(arr, 3)

4

In [63]:
arr1 = np.array([0, 1, 2, 3, 0, 4])

In [64]:
np.count_nonzero(arr1)

4

In [65]:
arr1 > 0

array([False,  True,  True,  True, False,  True])

In [66]:
np.where(arr1 > 0)

(array([1, 2, 3, 5], dtype=int64),)

In [67]:
np.extract(arr1 > 0, arr1)

array([1, 2, 3, 4])

In [68]:
arr = np.array([5, 6, 1, 2, 8, 9])

In [69]:
np.sort(arr)

array([1, 2, 5, 6, 8, 9])

In [70]:
np.searchsorted(arr, 7)

4

In [71]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

In [72]:
# matrix >> 2d array

In [73]:
import numpy.matlib as nm

In [74]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [75]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
# NumPy linear algebra

In [77]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [78]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [79]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [80]:
a = np.array([[7, 5, -3], [3, -5, 2], [5, 3, -7]])

In [81]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [82]:
b = np.array([16, -8, 0])

In [83]:
b

array([16, -8,  0])

In [84]:
np.linalg.solve(a, b)

array([1., 3., 2.])

In [85]:
arr1

array([[2, 3],
       [4, 5]])

In [86]:
np.linalg.det(arr1)

-2.0

In [87]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])