In [1]:
import numpy as np      # 2005 by Travis Oliphant

In [2]:
np.__version__

'1.26.3'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
# Why numpy?
# mathematical function
# Faster

In [5]:
l = [1, 2, 3, 4, 5]

In [6]:
arr = np.array(l)

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
type(np.array(l))

numpy.ndarray

In [9]:
arr.ndim

1

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.ndim

2

In [14]:
l = [1, 2, 3, 4]

In [15]:
np.matrix(l)        # Matrix will be by default 2d

matrix([[1, 2, 3, 4]])

In [16]:
# np.matrix([[[1, 2], [5, 6], [7, 8]]])

# ValueError: matrix must be 2-dimensional

In [17]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [18]:
# more way to convert to array
np.asarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [19]:
np.asanyarray([[[1, 2], [5, 6], [7, 8]]])  # Convert the input to an ndarray, but pass ndarray subclass through.

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [20]:
mat = np.matrix(l)

In [21]:
mat

matrix([[1, 2, 3, 4]])

In [22]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [23]:
t = ([1, 2, 3], [4, 5, 6])

In [24]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a = 5
np.array(a)

array(5)

In [26]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [27]:
arr[3]

4

In [28]:
a = arr     # This copy called Shallow Copy

In [29]:
a

array([1, 2, 3, 4, 5])

In [30]:
arr[0] = 1000

In [31]:
arr

array([1000,    2,    3,    4,    5])

In [32]:
a

array([1000,    2,    3,    4,    5])

In [33]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [34]:
a = arr.copy()      # This copy called Deep Copy

In [35]:
a

array([1, 2, 3, 4, 5])

In [36]:
arr[0] = 1000

In [37]:
arr

array([1000,    2,    3,    4,    5])

In [38]:
a

array([1, 2, 3, 4, 5])

In [39]:
# to create array >> .array, .asarray, asanyarray, deep copy, shallow copy

In [40]:
# There are multiple ways to generating arrays

In [41]:
np.fromfunction(lambda i, j: i == j, shape=(3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [42]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr

array([1000,    2,    3,    4,    5])

In [44]:
arr.shape

(5,)

In [45]:
arr1.shape

(2, 3)

In [46]:
arr.size

5

In [47]:
arr1.size

6

In [48]:
np.fromfunction(lambda i, j: i == j, shape=(3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [49]:
np.fromfunction(lambda i, j: i * j, shape=(3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [50]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [51]:
iterable = (i * i for i in range(5))

In [52]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [53]:
np.fromstring('23 34 67', sep=' ')

array([23., 34., 67.])

In [54]:
np.fromstring('23,34,67', sep=',')

array([23., 34., 67.])

In [55]:
np.fromstring('Raj,Deba,Dev', sep=',')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_9900\4273490400.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Raj,Deba,Dev', sep=',')


array([], dtype=float64)

In [56]:
arr

array([1000,    2,    3,    4,    5])

In [57]:
arr.shape

(5,)

In [58]:
arr.size

5

In [59]:
arr.dtype

dtype('int32')

In [60]:
l = [1, 2, 3, "Rajdip"]
arr = np.array(l)
arr.dtype

dtype('<U11')

In [61]:
arr

array(['1', '2', '3', 'Rajdip'], dtype='<U11')

In [62]:
list(range(5))

[0, 1, 2, 3, 4]

In [63]:
range(5)

range(0, 5)

In [64]:
# list(range(1.0, 2.10))

# TypeError: 'float' object cannot be interpreted as an integer

In [65]:
list(np.arange(0.1, 10.2, 0.1))

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [66]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [67]:
np.logspace(1, 5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [68]:
np.logspace(1, 5, 10, base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [69]:
arr1 = np.zeros(5)

In [70]:
arr1.shape

(5,)

In [71]:
arr1

array([0., 0., 0., 0., 0.])

In [72]:
arr1.ndim

1

In [73]:
arr2 = np.zeros((3, 4))
arr2.shape

(3, 4)

In [74]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
arr2.ndim

2

In [76]:
arr3 = np.zeros((1, 3, 4))
arr3.shape

(1, 3, 4)

In [77]:
arr3.ndim

3

In [78]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [79]:
arr4 = np.zeros((1, 1, 3, 4))
arr4.shape

(1, 1, 3, 4)

In [80]:
arr4.ndim

4

In [81]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [82]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [83]:
arr = np.ones((3,4))

In [84]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [86]:
arr * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [87]:
np.array([[[[[[[[[[[[[[1, 1, 1, 1, 1, 1]]]]]]]]]]]]]])

array([[[[[[[[[[[[[[1, 1, 1, 1, 1, 1]]]]]]]]]]]]]])

In [88]:
# np.twos((2, 3))

# AttributeError: module 'numpy' has no attribute 'twos'

In [89]:
l = [1, 2, 3, 4, 5, "Rajdip"]
arr = np.array(l)
arr.dtype

dtype('<U11')

In [90]:
arr

array(['1', '2', '3', '4', '5', 'Rajdip'], dtype='<U11')

In [ ]:
# What is NumPy?
# What is Array?
# List vs Array?
# Why Array is faster than list?